version: '2'
mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: mysql
    MYSQL_USER: root
    MYSQL_PASSWORD: secret

  ports:
    "3306:3306"