version: "3"

services:
  mysql-service:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restapi
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  springbootdb:
    image: springbootdb:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
